### ISSUE TITLE
Πρόβλημα με το νέο API του ΟΑΣΘ 

### ISSUE THREAD

**Issue by FearMyGaze** [teogramm/oasth#2]
Με την αλλαγή του API όπου έγινε από την πλευρά του ΟΑΣΘ το development της βιβλιοθήκης συνεχίζεται;

**Comment by teogramm** [comment]
Πλέον δε ζω στη Θεσσαλονίκη και έχει καιρό από τότε που ασχολήθηκα με τη βιβλιοθήκη, οπότε δεν θα την ενημερώσω. Θα βάλω και ένα notice στο README.

**Comment by FearMyGaze** [comment]
Αν δεν σου είναι δύσκολο μπόρεις να μου πείς με ποιό τρόπο βρήκες τα endpoints ;

**Comment by teogramm** [comment]
Με HTTP capture την πρώτη φορά που ανοίγεις την εφαρμογή. Απ' ότι θυμάμαι, τα δεδομένα που επιστρέφει μοιάζουν με GTFS αλλά δεν περιέχονται όλα τα αρχεία για φτιάξεις το feed.

**Comment by FearMyGaze** [comment]
Ωραία ευχαριστώ πολύ για την βοήθεια.
